db.url=jdbc:mysql://localhost:3306/cine
db.user=mysqlUser
db.password=mysqlPass
db.driver=com.mysql.jdbc.Driver


#auth de MONGODB
db.mongo.uri=mongodb://localhost:27017
db.mongo.name=pelicula

#auth de POSTGRESQL
db.pg.url=jdbc:postgresql://localhost:5432/postgres
db.pg.user=postgres
db.pg.pass=alba2004
