# auth de MYSQL
db.url=jdbc:mysql://localhost:3306/cine
db.user=admin
db.password=admin
db.driver=com.mysql.cj.jdbc.Driver

#auth de MONGODB
db.mongo.uri=mongodb://localhost:27017
db.mongo.name=pelicula

#auth de POSTGRESQL
db.pg.url=jdbc:postgresql://localhost:5432/postgres
db.pg.user=postgres
db.pg.pass=morcilla01
